[package]
name = "big_factorial"
version = "0.1.0"
edition = "2021"
description = "Tool to calculate factorials of large numbers"
repository = "https://github.com/Wattsy2020/big_factorial"
license = "MIT"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
malachite = "=0.4.16"
